#!/usr/bin/env python3
"""Render AUDIT/ledger.md from AUDIT/ledger.json (the machine-readable source of truth).

Usage: python3 AUDIT/tools/render_ledger.py            # rewrite ledger.md
       python3 AUDIT/tools/render_ledger.py --status   # print the one-line status header
"""
from __future__ import annotations

import json
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "ledger.json"
DST = ROOT / "ledger.md"

STATUSES = ["START", "PROGRESS", "TEST", "AUDIT", "DONE", "BLOCKED"]
SEVERITY_ORDER = {"S0": 0, "S1": 1, "S2": 2, "S3": 3}
FIELDS = [
    ("id", "id"), ("severity", "severity"), ("module", "project/module"), ("location", "file:line"),
    ("title", "title"), ("category", "category"), ("status", "status"), ("host", "host-used"),
    ("discovered_by", "discovered-by"), ("evidence_before", "evidence-before"),
    ("fix_summary", "fix-summary"), ("evidence_after", "evidence-after"), ("commit", "commit sha"),
    ("notes", "notes"), ("blocked_reason", "blocked-reason"),
]


def load() -> dict:
    return json.loads(SRC.read_text())


def counts(tasks: list[dict]) -> Counter:
    return Counter(t["status"] for t in tasks)


def status_line(data: dict) -> str:
    tasks = data["tasks"]
    c = counts(tasks)
    done = c["DONE"]
    blocked = c["BLOCKED"]
    open_ = len(tasks) - done - blocked
    new = sum(1 for t in tasks if t.get("session") == data["session"])
    return f"known-total:{len(tasks)} done:{done} open:{open_} blocked:{blocked} new-this-session:{new}"


def md_escape(value) -> str:
    text = "" if value is None else str(value)
    return text.replace("|", "\\|").replace("\n", "<br>")


def render(data: dict) -> str:
    tasks = sorted(data["tasks"], key=lambda t: (SEVERITY_ORDER.get(t["severity"], 9), t["id"]))
    c = counts(tasks)
    out: list[str] = []
    out.append("# Audit ledger (§8) — source of truth is `ledger.json`; this file is generated by `tools/render_ledger.py`\n")
    out.append(f"Session: `{data['session']}` · branch `{data['branch']}` · baseline commit `{data['baseline_commit']}`\n")
    out.append(f"**{status_line(data)}**\n")
    out.append("| status | count |\n|---|---|")
    for s in STATUSES:
        out.append(f"| {s} | {c[s]} |")
    out.append("")
    out.append("Status gates: START (reproduced/proven + expected behaviour written) → PROGRESS (diff) → TEST (failing-before/passing-after test pasted, full suite green, no new warnings) → AUDIT (cold re-read, all scanners re-run, no baseline regression, no new placeholder) → DONE (committed atomically). BLOCKED needs reason + what was tried + ≥2 options for a human.\n")

    for heading, pred in [
        ("Open S0 / S1", lambda t: t["severity"] in ("S0", "S1") and t["status"] not in ("DONE", "BLOCKED")),
        ("Blocked", lambda t: t["status"] == "BLOCKED"),
        ("Open S2 / S3", lambda t: t["severity"] in ("S2", "S3") and t["status"] not in ("DONE", "BLOCKED")),
        ("Done", lambda t: t["status"] == "DONE"),
    ]:
        rows = [t for t in tasks if pred(t)]
        out.append(f"## {heading} ({len(rows)})\n")
        if not rows:
            out.append("_none_\n")
            continue
        out.append("| id | sev | module | file:line | title | category | status | commit |\n|---|---|---|---|---|---|---|---|")
        for t in rows:
            out.append("| " + " | ".join(md_escape(t.get(k, "")) for k in ["id", "severity", "module", "location", "title", "category", "status", "commit"]) + " |")
        out.append("")

    out.append("## Full records\n")
    for t in sorted(tasks, key=lambda t: t["id"]):
        out.append(f"### {t['id']} · {t['severity']} · {t['status']} · {t['title']}\n")
        for key, label in FIELDS:
            if key in ("id", "severity", "status", "title"):
                continue
            val = t.get(key)
            if val in (None, "", []):
                continue
            out.append(f"- **{label}:** {md_escape(val)}")
        out.append("")
    return "\n".join(out) + "\n"


def main() -> int:
    data = load()
    ids = [t["id"] for t in data["tasks"]]
    if len(ids) != len(set(ids)):
        print("duplicate ids in ledger.json", file=sys.stderr)
        return 1
    for t in data["tasks"]:
        if t["status"] not in STATUSES:
            print(f"{t['id']}: bad status {t['status']}", file=sys.stderr)
            return 1
        if t["severity"] not in SEVERITY_ORDER:
            print(f"{t['id']}: bad severity {t['severity']}", file=sys.stderr)
            return 1
        if t["status"] == "BLOCKED" and not t.get("blocked_reason"):
            print(f"{t['id']}: BLOCKED without blocked_reason", file=sys.stderr)
            return 1
        if t["status"] == "DONE" and not t.get("commit"):
            print(f"{t['id']}: DONE without commit", file=sys.stderr)
            return 1
    if "--status" in sys.argv:
        print(status_line(data))
        return 0
    DST.write_text(render(data))
    print(status_line(data))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
